CREATE TABLE IF NOT EXISTS `pessoas` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT,
  `fk_creas_atual` tinyint unsigned NOT NULL,
  `fk_mse` tinyint unsigned NOT NULL,
  `fk_tec_ref` int  NOT NULL,
  `fk_ubs` smallint unsigned,
  `fk_sas` tinyint unsigned NOT NULL,
  `fk_servico_familia` tinyint unsigned DEFAULT NULL,
  `fk_distrito_servico` tinyint unsigned NOT NULL,
  `fk_medidas` tinyint unsigned NOT NULL,
  `fk_creas_origem` tinyint unsigned DEFAULT NULL,
  `nome` varchar(100) NOT NULL,
  `nome_social` varchar(100) DEFAULT NULL,
  `dt_nasc` date NOT NULL,
  `cpf` varchar(11) DEFAULT NULL,
  `nis` varchar(11) DEFAULT NULL,
  `cartao_sus` varchar(18) DEFAULT NULL,
  `nome_da_mae` varchar(100) NOT NULL,
  `nome_do_pai` varchar(100) DEFAULT NULL,
  `nome_responsavel` varchar(100) DEFAULT NULL,
  `sexo` char(1) NOT NULL,
  `fk_raca` tinyint unsigned NOT NULL,
  `fk_nacionalidade` tinyint unsigned NOT NULL,
  -- `indicacao_sigilo` tinyint(1) NOT NULL,
  `fk_genero` tinyint unsigned DEFAULT NULL,
  `fk_orientacao_sexual` tinyint unsigned DEFAULT NULL,
  `fk_estado_civil` tinyint unsigned NOT NULL,
  `matriculado` tinyint(1) NOT NULL,
  `alfabetizado` tinyint(1) NOT NULL,
  `fk_cicloEstudo` tinyint unsigned DEFAULT NULL,
  `numeroRa` varchar(11) DEFAULT NULL,
  `fk_tipoEscola` tinyint unsigned DEFAULT NULL,
  `fk_ensinoModalidade` tinyint unsigned DEFAULT NULL,
  `frequenciaAula` tinyint(1) DEFAULT NULL,
  `concluiuCurso` tinyint(1) DEFAULT NULL,
  `fk_paroudeEstudar` tinyint unsigned DEFAULT NULL,
  `possui_deficiencia` tinyint(1) NOT NULL,
  `fk_deficiencia` int unsigned DEFAULT NULL,
  `fk_trabalho` tinyint unsigned DEFAULT NULL,
  `necessita_cuidados_terceiros` tinyint(1) NOT NULL,
  `possui_demanda_saude` tinyint(1) NOT NULL,
  `saude` varchar(100) DEFAULT NULL,
  `possui_demanda_saude_mental` tinyint(1) NOT NULL,
  `saude_mental` varchar(100) DEFAULT NULL,
  `acompanhamento_saude` tinyint(1) DEFAULT NULL,
  `faz_uso_de_medicamentos` tinyint(1) NOT NULL,
  `medicamentos` varchar(100) DEFAULT NULL,
  `faz_uso_de_medicamentos_controlados` tinyint(1) NOT NULL,
  `medicamentos_controlados` varchar(100) DEFAULT NULL,
  `possui_trabalho` tinyint(1) DEFAULT NULL,
  `possui_familia_em_servico` tinyint(1) NOT NULL,
  `gestante` tinyint(1) DEFAULT NULL,
  `parceira_gestante` tinyint(1) DEFAULT NULL,
  `lactante` tinyint(1) DEFAULT NULL,
  `possui_filhos` tinyint(1) NOT NULL,
  `responsavel_por_pcd` tinyint(1) NOT NULL,
  `adolescente_com_trajetoria_de_acolhimento` tinyint(1) NOT NULL,
  `fk_alcool_ou_drogas` tinyint unsigned NOT NULL,
  `caps` tinyint(1) DEFAULT NULL,
  `curso` tinyint(1) NOT NULL,
  `fk_processos` int unsigned NOT NULL,
  `fk_distrito_pessoa` tinyint unsigned NOT NULL,
  `cep` varchar(8) NOT NULL,
  `bairro` varchar(100) NOT NULL,
  `rua` varchar(100) NOT NULL,
  `numero` int unsigned NOT NULL,
  `complemento` varchar(255) DEFAULT NULL,
  `dt_cadastro` date NOT NULL,
  `dt_atualizacao` date NOT NULL,
  `dt_desligamento` date DEFAULT NULL,
  `ativo_inativo` tinyint(1) NOT NULL,
  `listar_cursos` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_cicloEstudo` (`fk_cicloEstudo`),
  KEY `fk_tipoEscola` ( `fk_tipoEscola`),
  KEY `fk_ensinoModalidade` ( `fk_ensinoModalidade`),
  KEY `fk_paroudeEstudar` (`fk_paroudeEstudar`),
  KEY `fk_creas_atual` (`fk_creas_atual`),
  KEY `fk_creas_origem` (`fk_creas_origem`),
  KEY `fk_mse` (`fk_mse`),
  KEY `fk_tec_ref` (`fk_tec_ref`),
  KEY `fk_ubs` (`fk_ubs`),
  KEY `fk_sas` (`fk_sas`),
  KEY `fk_servico_familia` (`fk_servico_familia`),
  KEY `fk_distrito_servico` (`fk_distrito_servico`),
  KEY `fk_raca` (`fk_raca`),
  KEY `fk_nacionalidade` (`fk_nacionalidade`),
  KEY `fk_genero` (`fk_genero`),
  KEY `fk_orientacao_sexual` (`fk_orientacao_sexual`),
  KEY `fk_estado_civil` (`fk_estado_civil`),
  KEY `fk_deficiencia` (`fk_deficiencia`),
  KEY `fk_trabalho` (`fk_trabalho`),
  KEY `fk_alcool_ou_drogas` (`fk_alcool_ou_drogas`),
  KEY `fk_processos` (`fk_processos`),
  KEY `fk_distrito_pessoa` (`fk_distrito_pessoa`),
  KEY `fk_medidas` (`fk_medidas`),
  CONSTRAINT `pessoas_ibfk_1` FOREIGN KEY (`fk_creas_atual`) REFERENCES `creas` (`ID`),
  CONSTRAINT `pessoas_ibfk_10` FOREIGN KEY (`fk_orientacao_sexual`) REFERENCES `orientacao_sexual` (`ID`),
  CONSTRAINT `pessoas_ibfk_11` FOREIGN KEY (`fk_estado_civil`) REFERENCES `estado_civil` (`ID`),
  CONSTRAINT `pessoas_ibfk_13` FOREIGN KEY (`fk_deficiencia`) REFERENCES `deficiencia` (`ID`),
  CONSTRAINT `pessoas_ibfk_14` FOREIGN KEY (`fk_trabalho`) REFERENCES `trabalho` (`ID`),
  CONSTRAINT `pessoas_ibfk_16` FOREIGN KEY (`fk_processos`) REFERENCES `processos` (`ID`),
  CONSTRAINT `pessoas_ibfk_17` FOREIGN KEY (`fk_distrito_pessoa`) REFERENCES `distrito` (`ID`),
  CONSTRAINT `pessoas_ibfk_18` FOREIGN KEY (`fk_medidas`) REFERENCES `medidas_mse` (`ID`),
  CONSTRAINT `pessoas_ibfk_19` FOREIGN KEY (`fk_alcool_ou_drogas`) REFERENCES `alcool_ou_drogas` (`ID`),
  CONSTRAINT `pessoas_ibfk_20` FOREIGN KEY (`fk_cicloEstudo`) REFERENCES `cicloEstudo` (`ID`),
  CONSTRAINT `pessoas_ibfk_21` FOREIGN KEY (`fk_tipoEscola`) REFERENCES `tipoEscola` (`ID`),
  CONSTRAINT `pessoas_ibfk_87` FOREIGN KEY (`fk_ensinoModalidade`) REFERENCES `ensinoModalidade` (`ID`),
  CONSTRAINT `pessoas_ibfk_23` FOREIGN KEY (`fk_paroudeEstudar`) REFERENCES `paroudeEstudar` (`ID`),
  CONSTRAINT `pessoas_ibfk_2` FOREIGN KEY (`fk_creas_origem`) REFERENCES `creas` (`ID`),
  CONSTRAINT `pessoas_ibfk_3` FOREIGN KEY (`fk_mse`) REFERENCES `mse` (`ID`),
  CONSTRAINT `pessoas_ibfk_43` FOREIGN KEY (`fk_tec_ref`) REFERENCES `usuarios` (`ID`),
  CONSTRAINT `pessoas_ibfk_99` FOREIGN KEY (`fk_ubs`) REFERENCES `ubs` (`ID`),
  CONSTRAINT `pessoas_ibfk_4` FOREIGN KEY (`fk_sas`) REFERENCES `sas` (`ID`),
  CONSTRAINT `pessoas_ibfk_70` FOREIGN KEY (`fk_servico_familia`) REFERENCES `servico_familia` (`ID`),
  CONSTRAINT `pessoas_ibfk_5` FOREIGN KEY (`fk_distrito_servico`) REFERENCES `distrito` (`ID`),
  CONSTRAINT `pessoas_ibfk_6` FOREIGN KEY (`fk_raca`) REFERENCES `raca` (`ID`),
  CONSTRAINT `pessoas_ibfk_7` FOREIGN KEY (`fk_nacionalidade`) REFERENCES `nacionalidade` (`ID`),
  CONSTRAINT `pessoas_ibfk_9` FOREIGN KEY (`fk_genero`) REFERENCES `genero` (`ID`)
);