CREATE TABLE IF NOT EXISTS `sas` (
  `ID` tinyint unsigned NOT NULL AUTO_INCREMENT,
  `descricao` varchar(100) NOT NULL,
  `ativo_inativo` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT IGNORE INTO `sas` (`ID`, `descricao`, `ativo_inativo`) VALUES
	(1,'SÉ', 1),
	(2,'BUTANTÃ', 1),
	(3,'LAPA', 1),
	(4,'PINHEIROS', 1),
	(5,'ARICANDUVA-FORMOSA-CARRÃO', 1),
	(6,'MOOCA', 1),
	(7,'PENHA', 1),
	(8,'VILA PRUDENTE', 1),
	(9,'SAPOPEMBA', 1),
	(10,'CIDADE TIRADENTES', 1),
	(11,'ERMELINO MATARAZZO', 1),
	(12,'GUAIANASES', 1),
	(13,'ITAIM PAULISTA', 1),
	(14,'ITAQUERA', 1),
	(15,'SÃO MATEUS', 1),
	(16,'SÃO MIGUEL', 1),
	(17,'JAÇANÃ-TREMEMBÉ', 1),
	(18,'SANTANA-TUCURUVI', 1),
	(19,'VILA MARIA - VILA GUILHERME', 1),
	(20,'CASA VERDE - CACHOEIRINHA', 1),
	(21,'FREGUESIA - BRASILÂNDIA', 1),
	(22,'PERUS', 1),
	(23,'PIRITUBA', 1),
	(24,'IPIRANGA', 1),
	(25,'JABAQUARA', 1),
	(26,'VILA MARIANA', 1),
	(27,'CAMPO LIMPO', 1),
	(28,'CAPELA DO SOCORRO', 1),
	(29,'CIDADE ADEMAR', 1),
	(30,"M'BOI MIRIM", 1),
	(31,'PARELHEIROS', 1),
	(32,'SANTO AMARO', 1);